### ISSUE TITLE
Question: How to running the service with Docker

### ISSUE THREAD

**Issue by alexanderbikk** [Azure/pcs-simulation-webui#219]
Hello,

I'm trying to run the service with Docker but not found the steps how to do it(documentations etc)/ Now I'm investigating the folder pcs-simulation-webui\scripts\docker/ The build.cmd script create the pcs-simulation-webui\out\docker folder but I don't know what to do next? 

I'm trying to call the run.cmd script which run the Docker container but the service not working properly 
![image](https://user-images.githubusercontent.com/16937972/54838937-73229480-4cd2-11e9-8779-fbeb09c79589.png)

Actually I want to change  the variable simulationApiUrl in app.config.js to call my local simulator service(https://github.com/Azure/device-simulation-dotnet) which I have already started in Docker on localhost. And then build and run this Web UI in Docker image.

Can you help me?
Thanks in advance.

**Comment by peterfelts** [comment]
Hopefully my answer to your related question, [here](https://github.com/Azure/device-simulation-dotnet/issues/350), addressed this.

For what it's worth, when running locally I run the web UI from VS Code directly (npm start), and I run the storage adapter and the Simulation service both from Visual Studio directly.
